name: "FSN Hass Addon"
version: latest
description: "Homeassistant Addon for DFKI KI services"
init: false
slug: "fsn-hass-addon"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
docker_api: true
image: registry.dataspace.plaiful.org/hass/hass-addon
ports:
  8501/tcp: 8501
ingress: true
ingress_port: 8501
ingress_stream: true
startup: services
panel_icon: mdi:home-assistant
panel_title: "fsn-hass"