name: "FSN Hass Addon"
version: latest
description: "Homeassistant Addon for DFKI KI services"
init: false
slug: "fsn-hass-addon"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
docker_api: true
image: registry.dataspace.plaiful.org/hass/hass-addon:latest